### ISSUE TITLE
Backport

### ISSUE THREAD

**Issue by the-just-luke** [DeathsGun/ModManager#12]
Is a backport to 16 out of the question?

**Comment by DeathsGun** [comment]
Currently not but if the demand is this can be backported

**Comment by the-just-luke** [comment]
> Currently not but if there is demand this can be backported

good enough for me

**Comment by DeathsGun** [comment]
I have ported it to 1.16.5 but is has some bugs with the category list

**Comment by xSaVageAU** [comment]
Will there be a release for this port on here? I'd love to test it bugs or not

**Comment by DeathsGun** [comment]
I can upload you a build here when I'm home.

**Comment by DeathsGun** [comment]
Here it is:

[modmanager-1.1.0-alpha+1.16.jar.zip](https://github.com/DeathsGun/ModManager/files/7271366/modmanager-1.1.0-alpha%2B1.16.jar.zip)

**Comment by xSaVageAU** [comment]
Thankyou so much!!! I guess i'm one of the first people to try this hey :P my friend will be really happy if this works even to some degree as he hates browsing on modrinth and having to update buggy mods.

**Comment by xSaVageAU** [comment]
Did you happen to have Bedrockify mod installed? I just discovered on 1.17.1 version of Bedrockify breaks the category list.
I'm making a bug report on it as we speak

**Comment by xSaVageAU** [comment]
So installing the mod was unsuccessful. I tried on Curse and of course they don't have the latest Kotlin or Fabric version.
I installed the latest Kotlin from modrinth and installed fabric 0.11.7 and the game doesnt start. Is there something i'm missing?

These are the versions i have installed. I'm also using using Adoptium OpenJDK 16 if that matters
![Screenshot_2](https://user-images.githubusercontent.com/80192613/135726255-1118cbbc-5c6a-4c22-9e18-2a19a913a85b.png)

This is the "crash log"
https://pastebin.com/CANXZ4Zu

**Comment by DeathsGun** [comment]
The log is not complete

**Comment by DeathsGun** [comment]
You need to start minecraft and when it crashes upload `latest.log`in the logs directory

**Comment by xSaVageAU** [comment]
Oh my bad! https://pastebin.com/a88jhEiL here it is
I just assumed the latest text folder had the whole latest log lol

**Comment by xSaVageAU** [comment]
That first one is the latest.log file. thats all it gave me

**Comment by DeathsGun** [comment]
Ok that version isn't working because I'm using Java 16 features but minecraft 1.16.5 is only for Java 8

**Comment by xSaVageAU** [comment]
Ok good to know what the problem was so fast! I'll get back to you in a few minutes depending how long it takes me

**Comment by DeathsGun** [comment]
Oh thats something you can't fix I need to change all Java 16 features to Java 8's feature

**Comment by xSaVageAU** [comment]
Ok no worries :) Can't wait to try it :) Thanks again for letting me try it out i actually enjoy troubleshooting this stuff lol

**Comment by obp3ter** [comment]
I took a look, there's not much from what I can see, mostly the http client, because you have that only from java 11 and up. I had some problems with gradle, so I can't fix it for you right now.

**Comment by DeathsGun** [comment]
Oh you need to change the loom version from 0.9-SNAPSHOT to 0.7-SNAPSHOT also some methods for in the Config class need to be adjusted

**Comment by DeathsGun** [comment]
I have ported it to 1.16.5 it probably has some bugs but it should work for the most part
[modmanager-1.1.0-alpha+1.16.jar.zip](https://github.com/DeathsGun/ModManager/files/7274196/modmanager-1.1.0-alpha%2B1.16.jar.zip)
:

**Comment by obp3ter** [comment]
I'll give it a try right now

**Comment by obp3ter** [comment]
Some mods can't be updated no matter what, some are not recognized as being installed(I'm guessing, the ones that were installed from curseforge), and the buttons look weird:
![image](https://user-images.githubusercontent.com/15703843/135765677-b6b6b28b-e76e-4afe-92a3-30d9da80fce0.png)
But other than that, good job, I'm very happy, that it's available for 1.16 as well.

**Comment by DeathsGun** [comment]
Have you bedrockify installed?

**Comment by obp3ter** [comment]
No, here are my mods, but it doesn't matter, I'll still be using it as it is.

- BetterPingDisplay-Fabric-1.16.5-1.1.jar
- BetterThirdPerson-Fabric-1.16.4-1.5.0.jar
- Blur-2.1.0-1.16+fabric.jar
- ChunkBorders-0.5.0-fabric-mc1.16.5.jar
- DripSounds-0.2.1-1.16.jar
- DynamicSoundFilters-1.2.0+1.16.5.jar
- InvMove-fabric-1.16-0.1.0.jar
- InventorySorter-1.7.9-1.16.jar
- Loading-Timer-1.4.3.jar
- NoFog-1.16.2b1-Fabric.jar
- OfflineSkins-1.16.5-v1-fabric.jar
- PresenceFootsteps-r29+1.16.4.jar
- RoughlyEnoughItems-5.12.248.jar
- SmoothScrollingEverywhere-3.0.3-unstable.jar
- TRansliterationLib-1.0.4.jar
- amecs-1.3.4+mc.1.16.3.jar
- antighost-1.16.5-fabric0.30.0-1.1.3.jar
- appleskin-fabric-mc1.16.x-2.1.3.jar
- architectury-1.23.33-fabric.jar
- audiooutput-1.16.2-0.0.3.jar
- beenfo-1.16.5-fabric0.30.0-1.3.1.jar
- bettermounthud-1.0.1.jar
- betterworldlist-1.0.4-1.16.2.jar
- capes-1.1.2.jar
- carpet-addons-1.16.4-1.0.8+v210130.jar
- carpet-autocraftingtable-1.16.4-1.4.17_build2.jar
- carpet-extra-1.16.5-1.4.23.jar
- carpet-tis-addition-mc1.16.5-1.22.0+build.677.jar
- chat_heads-0.2.2+1.16.2.jar
- chatsounds-1.0.0.jar
- cleancut-mc1.16-2.1-fabric.jar
- clear-skies-mc116-1.5.57.jar
- cleardespawn-1.16.5-fabric0.30.0-1.1.1.jar
- cloth-config-4.11.26-fabric.jar
- colormatic-2.2.9+mc.1.16.5.jar
- connected-block-textures-0.1.3+1.16.jar
- continuebutton-1.0.2.jar
- cullleaves-2.1.0.jar
- dark-loading-screen-1.6.3.jar
- debrand-1.0.2.jar
- durabilityviewer-1.16.5-fabric0.30.0-1.10.jar
- dynamic-fps-2.0.2.jar
- dynamic-music-1.2.0.1.jar
- enhancedblockentities-0.4--1.16.x.jar
- extra-sounds-1.4.0.jar
- fabric-api-0.40.1+1.16.jar
- fabric-carpet-1.16.5-1.4.44+v210714.jar
- fabric-language-kotlin-1.6.5+kotlin.1.5.31.jar
- fabricmod_VoxelMap-1.10.15_for_1.16.5.jar
- fabrishot-1.4.0.jar
- fastbench-2.3.jar
- fastfurnace-2.4.jar
- flighthelper-1.16.5-fabric0.30.0-1.2.1.jar
- headdowndisplay-1.0.1+1.16.jar
- held-item-info-1.1.3.jar
- horse-stats-vanilla-4.1.8.jar
- hwyla-addon-horseinfo-0.2.2-1.16.1.jar
- hydrogen-fabric-mc1.16.5-0.2.jar
- indium-1.0.0+mc1.16.5.jar
- iris-and-sodium-mc1.16.5-1.1.2+build.4.jar
- isometric-renders-0.1.10.jar
- item-model-fix-1.0.2+1.16.jar
- itemscroller-fabric-1.16.4-0.15.0-dev.20210111.205029.jar
- ivan-carpet-addition-mc1.16.4-1.4.0+build.101.jar
- krypton-0.1.2.jar
- lambdabettergrass-fabric-1.0.3+1.16.jar
- lambdacontrols-fabric-1.6.0+1.16.jar
- lambdynamiclights-fabric-1.3.4+1.16.jar
- litematica-fabric-1.16.4-0.0.0-dev.20210612.170003.jar
- malilib-fabric-1.16.4-0.10.0-dev.21+arne.5.jar
- minihud-fabric-1.16.4-0.19.0-dev.20210129.142059.jar
- minimalmenu-1.16.5-0.0.5.jar
- minimalmenu-1.16.5-0.0.7.jar
- minitweaks-1.0.15.jar
- modmanager-1.1.0-alpha+1.16.jar
- modmenu-1.16.21.jar
- modmenu-1.16.22.jar
- modupdater-1.1.11+1.16.2-rc2.jar
- monsters-in-the-closet-1.0.2+1.16.jar
- multiconnect-1.3.36.jar
- nameless-servers-1.0.0+1.16.jar
- nmuk-1.0.0+mc1.16.4.jar
- notenoughanimations-1.2.4.jar
- notenoughcrashes-3.2.0-fabric.jar
- phosphor-fabric-mc1.16.3-0.7.2+build.12.jar
- ping-1.2.1.jar
- pling-1.3.0.jar
- reloadAudioDriver-1.0.1.jar
- rer-2.1.5.jar
- roughly-searchable-2.1.3+1.16.5.jar
- rug-1.16.5-1.1.12.jar
- scarpet-additions-1.16.5-1.4.38.jar
- scarpet-os-utils-1.16.5-1.4.40-v1.0.4-SNAPSHOT.jar
- seamless-loading-screen-1.3.4+1.16.2.jar
- sheepconsistency-1.0.2.jar
- shulkerboxtooltip-2.3.7+1.16.5.jar
- slight-gui-modifications-1.7.1.jar
- smoothboot-fabric-1.16.5-1.6.0.jar
- sodium-extra-0.3.2.jar
- speedtrading-2.0.1.jar
- statssearch-1.16.5-fabric0.30.0-1.0.1.jar
- tooltipfix-1.0.2-1.16.jar
- transparent-2.1.0-fabric.jar
- tweakeroo-fabric-1.16.4-0.10.0-dev.20210303.123654.jar
- varied-mobs-1.0.0.jar
- whyamionfire-1.1.1.jar
- wthit-2.10.9-fabric.jar
- yosbr-0.1.1.jar

**Comment by obp3ter** [comment]
Oh, and the d is missing
![image](https://user-images.githubusercontent.com/15703843/135765866-c352ba0c-7d2a-4ff0-8673-586e49335607.png)

**Comment by DeathsGun** [comment]
Yeah thats an scaling issue which is also a bug in the 1.17.1 version

**Comment by DeathsGun** [comment]
Here is a new test version for 1.16.5! It's based on the 1.2.0 Branch with some patches.
For this one you will need:
- fabric-language-kotlin
- fabric-loader 0.12

[modmanager-1.2.0+1.16.jar.zip](https://github.com/DeathsGun/ModManager/files/7584125/modmanager-1.2.0%2B1.16.jar.zip)

**Comment by obp3ter** [comment]
It was compiled with java 16.

**Comment by DeathsGun** [comment]
Oh my bad I missed that one. I will need some time to change HTTP specific code because it uses the Java 11 HttpClient

**Comment by DeathsGun** [comment]
Fixed it here is a new build:
[modmanager-1.2.0+1.16.jar.zip](https://github.com/DeathsGun/ModManager/files/7594972/modmanager-1.2.0%2B1.16.jar.zip)

**Comment by obp3ter** [comment]
I finally managed to update to fabric 12 and test this out. It works well, as far as I can see. The problem with versions being offered beeing older than the one installed is still a problem, but when I have more time, probably next year I'll look into it.

**Comment by DeathsGun** [comment]
I'm working currently on a fix for that one which is more detailed here #101 which will also gets backported to 1.16

**Comment by obp3ter** [comment]
Nice. Although thats not exactly what I meant. Yeah I also have a few mods where it differes a bit but it's the same version. I was thinking more about mods where it thinks that 2.10.11 is older than fabric-2.10.2. The same fix could apply if you are thinking about comparing not only what's the latest on modrinth but still it's a bit annoying.

**Comment by DeathsGun** [comment]
Hey i just merged all the 1.17 and 1.18 features into 1.16 can anyone test this version a little bit more extensively?
[modmanager-1.2.0+1.16.zip](https://github.com/DeathsGun/ModManager/files/7803271/modmanager-1.2.0%2B1.16.zip)

**Comment by obp3ter** [comment]
Nice. I don't really have a lot of time this week, but at the latest, during the weekend I can test it a bit.

**Comment by obp3ter** [comment]
![Screenshot (113)](https://user-images.githubusercontent.com/15703843/149208185-56abdf89-0d6b-4ed5-a108-4cc6b31ea92b.png)
Notifications keep popping up for me. And the number isn't even accurate. I had 5 updates available when I opened that tab.

**Comment by obp3ter** [comment]
> Nice. Although thats not exactly what I meant. Yeah I also have a few mods where it differes a bit but it's the same version. I was thinking more about mods where it thinks that 2.10.11 is older than fabric-2.10.2. The same fix could apply if you are thinking about comparing not only what's the latest on modrinth but still it's a bit annoying.

And this is still there

**Comment by DeathsGun** [comment]
With 1.2.2?

**Comment by luni3359** [comment]
I'm also experiencing that pop up on minecraft 1.18.1 on version 1.2.1, although the count seems to be correct.

https://user-images.githubusercontent.com/16832398/149229726-72c7b9f4-0e34-431e-b166-585ed6ecfa26.mp4

**Comment by luni3359** [comment]
There's no more notifications spam on 1.2.2!

**Comment by obp3ter** [comment]
So I managed to have a look at the newer version. I didn't notice, that you started making releases. The notification bug is not there anymore, but the versioning issue is. And now it is taking very very long until the mod looks for updates, and while doing so it consumes a lot of resources. My animated background is lagging while ModManager is looking for updates.

**Comment by luni3359** [comment]
I'm also having other issues, but I think we'd better make a separate issue for those.

**Comment by DeathsGun** [comment]
> And now it is taking very very long until the mod looks for updates, and while doing so it consumes a lot of resources. My animated background is lagging while ModManager is looking for updates.

Yeah I need to investigate that one, but I think it has something to do with the race condition fix
